version: "2017-09-20"
pipeline:
  - id: build
    type: script
    overlay: ci/python
    vm: small
    env:
      NODE_END: CI
    commands:
      - desc: Install dependencies
        cmd: |
          apt update
          apt install chromium-chromedriver -y
          pip3 install mkdocs \
                       mkdocs-material \
                       mkdocs-mermaid2-plugin \
                       mkdocs-pdf-with-js-plugin \
                       mkdocs-minify-plugin \
                       mkdocs-abs-rel-plugin \
                       mkdocs-git-revision-date-plugin \
                       mkdocs-render-swagger-plugin \
                       git+https://github.com/inuits/mkdocs-subsite \
                       mkdocs-snippet-plugin
      - desc: Build Docs
        cmd: |
          mkdocs build
          shopt -s extglob
          if [ "$CDP_PULL_REQUEST_NUMBER" ]; then
            mkdir -p site/pr/#{CDP_PULL_REQUEST_NUMBER}
            mv site/!(pr) site/pr/#{CDP_PULL_REQUEST_NUMBER}
            if [[ $(echo "#{CDP_BUILD_VERSION}" | grep -Eo '[0-9]+$') = 1 ]]; then
              git gh-comment Preview is available under:  https://studiotech.docs-test.zalando.net/pr/#{CDP_PULL_REQUEST_NUMBER}/
            fi
          fi
    artifacts:
      - type: docs
        name: studiotech
        path: site
