name: deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - run: pip3 install mkdocs \
                          mkdocs-material
      - run: mkdocs gh-deploy --force